CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    user_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL UNIQUE,
    authority VARCHAR(64) NOT NULL,
    CONSTRAINT FK_Authorities_Users FOREIGN KEY(user_id) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS USER_DETAILS_EXTRA (
    user_id BIGINT PRIMARY KEY,
    first_name VARCHAR(64),
    last_name VARCHAR(64),
    mail VARCHAR(64),
    birth_date DATE,
    CONSTRAINT FK_UserDetailsExtra_Users FOREIGN KEY (user_id) REFERENCES Users(id)
);